sudo: required
services:
  - docker

before_install:
  - docker build -t rakeshorange2018/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rakeshorange2018/react-test npm test -- --coverage

after_success:
  - docker build -t rakeshorange2018/multi-client ./client
  - docker build -t rakeshorange2018/multi-nginx ./nginx
  - docker build -t rakeshorange2018/multi-server ./server
  - docker build -t rakeshorange2018/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rakeshorange2018/multi-client
  - docker push rakeshorange2018/multi-nginx
  - docker push rakeshorange2018/multi-server
  - docker push rakeshorange2018/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-217012847344
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
